/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes_Java;

import com.google.gson.Gson;
import org.junit.Test;

import java.io.FileReader;
import java.io.IOException;
import java.io.Reader;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Random;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void testQuotes() {
        Gson gson = new Gson();
        Path path = Paths.get("../app/src/main/resources/recentquotes.json");
        try (Reader reader = new FileReader(path.toString())) {
            RecentQuotes[] recentQuotes = gson.fromJson(reader, RecentQuotes[].class);
            Random random = new Random();
            int index = random.nextInt(recentQuotes.length);
            String expected = "Today's Quote: \n" +
                    "Quote:  “It's easier to believe there's a monster under the bed if you've spent the last six months arguing with a monster.” \n" +
                    "author: Chuck Klosterman";
            String output = recentQuotes[10].toString();
            assertEquals(expected,output);
        } catch (IOException ex) {
            System.out.println("file not found ... " + ex.getMessage());
            assertTrue(false);
        }
    }





}
