/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes_Java;

import com.google.gson.Gson;

import java.io.FileReader;
import java.io.IOException;
import java.io.Reader;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Random;

public class App {
    public static void main(String[] args) throws IOException {
        Gson gson = new Gson();
        Path path = Paths.get("app/src/main/resources/recentquotes.json"); // for run from the IDE
//        Path path = Paths.get("../app/src/main/resources/recentquotes.json"); // for run from the CLI ' ./gradlew run '

        try (Reader reader = new FileReader(path.toString())) {

            RecentQuotes[] recentQuotes = gson.fromJson(reader, RecentQuotes[].class);
            Random random = new Random();
            int index = random.nextInt(recentQuotes.length);

            System.out.println(recentQuotes[index]);
        }
        catch (IOException ex) {
            System.out.println("file not found ... " + ex.getMessage());
        }


    }
}
